service: todosList

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-typescript

functions:
  createTodo:
    handler: ./src/functions/createTodo.handle
    events:
      - http:
          path: /todos/{user_id}
          method: POST
          cors: true
  getTodos:
    handler: ./src/functions/getTodos.handle
    events:
      - http:
          path: /todos/{id}
          method: GET
          cors: true

custom: 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - local
      - dev
    start:
      port: 8002
      inMemory: true
      migrate: true

resources:
  Resources:
    dbTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5